package com.application.market.config;

import com.application.market.entity.Category;
import com.application.market.entity.Product;
import com.application.market.repository.CategoryRepository;
import com.application.market.repository.ShopRepository;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

@Component
public class DataInitializer {

    @Autowired
    private CategoryRepository categoryRepository;

    @Autowired
    private ShopRepository shopRepository;

    public DataInitializer(CategoryRepository categoryRepository, ShopRepository shopRepository) {
        this.categoryRepository = categoryRepository;
        this.shopRepository = shopRepository;
    }

    private byte[] loadImage(String imagePath) {
        try {
            ClassPathResource resource = new ClassPathResource(imagePath);
            InputStream inputStream = resource.getInputStream();
            return inputStream.readAllBytes();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    @PostConstruct
    public void init() {
        addCategories();
        addProducts();
    }

    private void addCategories() {

        List<Category> categoriesList = List.of(
                new Category(1, "Fruits & Veges",
                        loadImage("static/images/category-thumb-1.jpg")),
                new Category(2, "Breads & Sweets",
                        loadImage("static/images/category-thumb-2.jpg")),
                new Category(3, "Wine",
                        loadImage("static/images/category-thumb-3.jpg")),
                new Category(4, "Beverages",
                        loadImage("static/images/category-thumb-4.jpg")),
                new Category(5, "Meat Products",
                        loadImage("static/images/category-thumb-5.jpg")),
                new Category(6, "Breads",
                        loadImage("static/images/category-thumb-6.jpg")),
                new Category(7, "Dairy & Eggs",
                        loadImage("static/images/category-thumb-7.jpg")),
                new Category(8, "Breads & Sweets",
                        loadImage("static/images/category-thumb-8.jpg")),
                new Category(9, "Breads & Sweets",
                        loadImage("static/images/category-thumb-1.jpg")),
                new Category(10, "Breads & Sweets",
                        loadImage("static/images/category-thumb-2.jpg")),
                new Category(11, "Breads & Sweets",
                        loadImage("static/images/category-thumb-3.jpg")),
                new Category(12, "Breads & Sweets",
                        loadImage("static/images/category-thumb-4.jpg")),
                new Category(13, "Breads & Sweets",
                        loadImage("static/images/category-thumb-5.jpg")),
                new Category(14, "Breads & Sweets",
                        loadImage("static/images/category-thumb-6.jpg")),
                new Category(15, "Breads & Sweets",
                        loadImage("static/images/category-thumb-7.jpg"))
        );

        categoryRepository.saveAll(categoriesList);

    }

    private void addProducts() {
        List<Product> productList = List.of(
                new Product(1L, categoryRepository.findById(1).get(),
                        "Eco Water Bottle",
                        "Reusable water bottle made from recycled materials",
                        15.99, 20, 4.5, 120,
                        loadImage("static/images/product-large-1.jpg")),
                new Product(2L, categoryRepository.findById(2).get(),
                        "Organic Almonds",
                        "High-quality organic almonds packed with nutrients",
                        25.50, 18, 4.8, 200,
                        loadImage("static/images/product-large-2.jpg")),
                new Product(3L, categoryRepository.findById(3).get(),
                        "Vintage Red Wine",
                        "A fine selection of organic vintage red wine",
                        45.00, 11, 4.9, 80,
                        loadImage("static/images/product-large-3.jpg")),
                new Product(4L, categoryRepository.findById(4).get(),
                        "Sparkling Water",
                        "Crisp sparkling water with natural minerals",
                        5.00, 10, 4.3, 150,
                        loadImage("static/images/product-large-4.jpg")),
                new Product(5L, categoryRepository.findById(5).get(),
                        "Grass-Fed Beef",
                        "Premium cuts of grass-fed beef",
                        50.00, 10, 4.6, 90,
                        loadImage("static/images/product-large-5.jpg")),
                new Product(6L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),
                new Product(7L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),
                new Product(8L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),
                new Product(9L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),
                new Product(10L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),
                new Product(11L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),
                new Product(12L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),
                new Product(13L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),
                new Product(14L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),
                new Product(15L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),
                new Product(16L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),
                new Product(17L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),
                new Product(18L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),
                new Product(19L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),
                new Product(20L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),
                new Product(21L, categoryRepository.findById(6).get(),
                        "Whole Wheat Rolls",
                        "Freshly baked whole wheat rolls",
                        3.50, 14, 4.5, 90,
                        loadImage("static/images/product-thumb-21.png")),
                new Product(22L, categoryRepository.findById(7).get(),
                        "Free-Range Eggs",
                        "Organic free-range eggs, high in quality",
                        6.50, 8, 4.9, 95,
                        loadImage("static/images/product-thumb-22.png")),
                new Product(23L, categoryRepository.findById(8).get(),
                        "Butter Cookies",
                        "Crispy and buttery homemade cookies",
                        8.50, 12, 4.8, 65,
                        loadImage("static/images/product-thumb-23.png")),
                new Product(24L, categoryRepository.findById(9).get(),
                        "Hazelnut Chocolate",
                        "Creamy hazelnut chocolate with 70% cocoa",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-24.png")),
                new Product(25L, categoryRepository.findById(10).get(),
                        "Parmesan Cheese",
                        "Aged Parmesan cheese, rich and flavorful",
                        14.99, 10, 4.9, 55,
                        loadImage("static/images/product-thumb-25.png")),
                new Product(26L, categoryRepository.findById(11).get(),
                        "French Baguette",
                        "Freshly baked French baguette",
                        4.99, 10, 4.6, 110,
                        loadImage("static/images/product-thumb-26.png")),
                new Product(27L, categoryRepository.findById(1).get(),
                        "Organic Apples",
                        "Fresh organic apples, full of nutrients",
                        3.99, 13, 4.7, 150,
                        loadImage("static/images/product-thumb-1.png")),
                new Product(28L, categoryRepository.findById(2).get(),
                        "Whole Wheat Bread",
                        "Whole grain wheat bread, freshly baked",
                        4.50, 11, 4.3, 120,
                        loadImage("static/images/product-thumb-2.png")),
                new Product(29L, categoryRepository.findById(3).get(),
                        "Red Wine",
                        "Fine selection of organic red wine",
                        30.00, 14, 4.8, 85,
                        loadImage("static/images/product-thumb-3.png")),
                new Product(30L, categoryRepository.findById(4).get(),
                        "Orange Juice",
                        "Freshly squeezed orange juice",
                        5.99, 8, 4.5, 60,
                        loadImage("static/images/product-thumb-4.png")),
                new Product(31L, categoryRepository.findById(5).get(),
                        "Free-Range Chicken",
                        "Premium quality free-range chicken",
                        20.99, 12, 4.6, 95,
                        loadImage("static/images/product-thumb-5.png")),
                new Product(32L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(33L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(34L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(35L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(36L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(37L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(38L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(39L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(40L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(41L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(42L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(43L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(44L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(45L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(46L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),
                new Product(47L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(48L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(49L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(50L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(51L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(52L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(53L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(54L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(55L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(56L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(57L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(58L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(59L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(60L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(61L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),
                new Product(62L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(63L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(64L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(65L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(66L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(67L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(68L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(69L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(70L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(71L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(72L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(73L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(74L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(75L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(76L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),
                new Product(77L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(78L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(79L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(80L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(81L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(82L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(83L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(84L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(85L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(86L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(87L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(88L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(89L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(90L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(91L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),
                new Product(92L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(93L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(94L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(95L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(96L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(97L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(98L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(99L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(100L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(101L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(102L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(103L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(104L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(105L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(106L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(107L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(108L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(109L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(110L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(111L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(112L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(113L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(114L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(115L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(116L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(117L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(118L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(119L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(120L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(121L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),
                new Product(122L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(123L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(124L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(125L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(126L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(127L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(128L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(129L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(130L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(131L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(132L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(133L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(134L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(135L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(136L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(137L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(138L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(139L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(140L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(141L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(142L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(143L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(144L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(145L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(146L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(147L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(148L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(149L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(150L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(151L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),
                new Product(152L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(153L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(154L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(155L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(156L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(157L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(158L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(159L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(160L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(161L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(162L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(163L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(164L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(165L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(166L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(167L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(168L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(169L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(170L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(171L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(172L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(173L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(174L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(175L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(176L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(177L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(178L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(179L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(180L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),
                new Product(181L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(182L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(183L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(184L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(185L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(186L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(187L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(188L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(189L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(190L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(191L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(192L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(193L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(194L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(195L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png")),

                new Product(196L, categoryRepository.findById(4).get(),
                        "Lemonade",
                        "Refreshing lemonade with natural ingredients",
                        4.99, 10, 4.5, 80,
                        loadImage("static/images/product-thumb-19.png")),

                new Product(197L, categoryRepository.findById(5).get(),
                        "Ground Beef",
                        "High-quality grass-fed ground beef",
                        10.99, 14, 4.8, 70,
                        loadImage("static/images/product-thumb-20.png")),

                new Product(198L, categoryRepository.findById(6).get(),
                        "Multigrain Bread",
                        "Freshly baked multigrain bread",
                        6.50, 8, 4.4, 80,
                        loadImage("static/images/product-thumb-6.png")),

                new Product(199L, categoryRepository.findById(7).get(),
                        "Organic Milk",
                        "High-quality organic milk from grass-fed cows",
                        3.99, 12, 4.7, 130,
                        loadImage("static/images/product-thumb-7.png")),

                new Product(200L, categoryRepository.findById(8).get(),
                        "Butter Croissants",
                        "Delicious buttery croissants, freshly baked",
                        7.99, 13, 4.9, 70,
                        loadImage("static/images/product-thumb-8.png")),

                new Product(201L, categoryRepository.findById(9).get(),
                        "Dark Chocolate",
                        "Premium dark chocolate, 85% cocoa",
                        8.99, 11, 4.8, 90,
                        loadImage("static/images/product-thumb-9.png")),

                new Product(202L, categoryRepository.findById(10).get(),
                        "Cheddar Cheese",
                        "Aged cheddar cheese, rich in flavor",
                        12.99, 11, 4.6, 65,
                        loadImage("static/images/product-thumb-10.png")),

                new Product(203L, categoryRepository.findById(11).get(),
                        "Sourdough Bread",
                        "Freshly baked sourdough bread",
                        4.99, 10, 4.7, 110,
                        loadImage("static/images/product-thumb-11.png")),

                new Product(204L, categoryRepository.findById(12).get(),
                        "Almond Butter",
                        "Smooth and creamy almond butter",
                        9.99, 10, 4.7, 85,
                        loadImage("static/images/product-thumb-12.png")),

                new Product(205L, categoryRepository.findById(13).get(),
                        "Beef Jerky",
                        "Grass-fed beef jerky, high in protein",
                        14.99, 13, 4.4, 75,
                        loadImage("static/images/product-thumb-13.png")),

                new Product(206L, categoryRepository.findById(14).get(),
                        "Greek Yogurt",
                        "Rich and creamy Greek yogurt",
                        3.49, 14, 4.8, 130,
                        loadImage("static/images/product-thumb-14.png")),

                new Product(207L, categoryRepository.findById(15).get(),
                        "Espresso Coffee",
                        "Premium espresso coffee beans",
                        13.99, 14, 4.9, 120,
                        loadImage("static/images/product-thumb-15.png")),

                new Product(208L, categoryRepository.findById(1).get(),
                        "Organic Bananas",
                        "Fresh and sweet organic bananas",
                        2.99, 16, 4.6, 200,
                        loadImage("static/images/product-thumb-16.png")),

                new Product(209L, categoryRepository.findById(2).get(),
                        "Chocolate Cake",
                        "Delicious homemade chocolate cake",
                        15.00, 14, 4.9, 60,
                        loadImage("static/images/product-thumb-17.png")),

                new Product(210L, categoryRepository.findById(3).get(),
                        "White Wine",
                        "Fine selection of organic white wine",
                        25.99, 13, 4.7, 55,
                        loadImage("static/images/product-thumb-18.png"))

        );

        shopRepository.saveAll(productList);

    }

}
